version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
#        aws_auth:
#          aws_access_key_id: AKIA2GB5QVA4PHBPUDHX  # can specify string literal values
#          aws_secret_access_key: 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
    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
      - run:
          name: run tests
          command: |
            ls -al
            docker build -t congtube .
            docker tag congtube:latest 700208687160.dkr.ecr.ap-northeast-2.amazonaws.com/congtube:latest
            docker push 700208687160.dkr.ecr.ap-northeast-2.amazonaws.com/congtube:latest