version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/congtube

    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
      - run:
          name: folder
          command: |
            ls -al
            pwd
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Deploy
          command: |
            aws configure set profile.prod.aws_access_key_id AKIA2GB5QVA4PHBPUDHX
            aws configure set profile.prod.aws_secret_access_key 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
            aws configure set profile.prod.region ap-northeast-2
            (aws ecr get-login --no-include-email --region ap-northeast-2)
            docker build -t congtube .
            docker tag congtube:latest 700208687160.dkr.ecr.ap-northeast-2.amazonaws.com/congtube:latest
            docker push 700208687160.dkr.ecr.ap-northeast-2.amazonaws.com/congtube:latest
