# Generated by Django 2.2.5 on 2019-10-22 15:29

import channels.models.channel
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='이름')),
                ('slug', models.SlugField()),
                ('image', models.ImageField(upload_to=channels.models.channel._channel_image_upload_to, verbose_name='프로필 이미지')),
                ('video', models.FileField(upload_to=channels.models.channel._channel_video_upload_to, verbose_name='대표 동영상')),
                ('description', models.TextField(verbose_name='설명')),
                ('is_display', models.BooleanField(blank=True, default=True, verbose_name='표시')),
                ('is_hot', models.BooleanField(blank=True, default=False, verbose_name='인기')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '채널',
                'verbose_name_plural': '채널',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='태그명')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': '태그',
                'verbose_name_plural': '태그',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='상품명')),
                ('price', models.PositiveIntegerField(verbose_name='가격')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channels.Channel')),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품',
            },
        ),
        migrations.AddField(
            model_name='channel',
            name='tags',
            field=models.ManyToManyField(to='channels.Tag'),
        ),
    ]
