# Generated by Django 2.2.5 on 2019-11-01 02:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['price'], 'verbose_name': '상품', 'verbose_name_plural': '상품'},
        ),
    ]
