# Generated by Django 2.2.6 on 2019-12-05 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0003_auto_20191205_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebrity',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
