# Generated by Django 2.2.5 on 2019-12-11 07:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0004_bestvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='goods_detail',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='굿즈 상세페이지'),
        ),
    ]
