# Generated by Django 2.2.5 on 2019-10-22 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import orders.models.order


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, '결제실패'), (2, '결제완료'), (3, '주문완료')], default=1)),
                ('merchant_uid', models.CharField(max_length=64)),
                ('reciever_name', models.CharField(max_length=16)),
                ('phonenumber', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=512)),
                ('amount', models.PositiveIntegerField(verbose_name='결제 금액')),
                ('video', models.FileField(blank=True, null=True, upload_to=orders.models.order._order_video_upload_to, verbose_name='동영상')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='channels.Channel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channels.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '주문',
                'verbose_name_plural': '주문',
            },
        ),
    ]
