# Generated by Django 2.2.5 on 2019-11-01 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': '주문', 'verbose_name_plural': '주문'},
        ),
    ]
