# Generated by Django 2.2.5 on 2019-11-27 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20191101_0253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancelreason', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': '취소사유',
                'verbose_name_plural': '취소사유',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='cancel',
            field=models.BooleanField(default=False, verbose_name='주문취소 알림 전송'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_alarm',
            field=models.BooleanField(default=False, verbose_name='영상업로드 알림 전송'),
        ),
        migrations.AlterField(
            model_name='order',
            name='message',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, '결제실패'), (2, '결제완료'), (3, '주문완료'), (4, '주문취소')], default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelreason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Cancel', verbose_name='취소사유'),
        ),
    ]
