# Generated by Django 2.2.5 on 2019-11-01 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': '후기', 'verbose_name_plural': '후기'},
        ),
    ]
