# Generated by Django 2.2.5 on 2019-10-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='이미지')),
                ('title', models.CharField(max_length=32, verbose_name='이름')),
                ('is_display', models.BooleanField(blank=True, default=True, verbose_name='노출')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '배너',
                'verbose_name_plural': '배너',
            },
        ),
    ]
